### ISSUE TITLE
SIMD Capacity not detected on M1

### ISSUE THREAD

**Issue by f-ij** [jakobnissen/ScanByte.jl#5]
I'm getting the following error on my M1 MacBook:
┌ 
Warning: SIMD capacity not detected by ScanByte, using scalar fallback
└ @ ScanByte ~/.julia/packages/ScanByte/eOQJf/src/ScanByte.jl:11

**Comment by jakobnissen** [comment]
Duplicate of #2 .
The problem is that I don't have a computer with an armv8 chip, so I can't test and develop the code.
