### ISSUE TITLE
Use SIMD.jl for code generation

### ISSUE THREAD

**Issue by eschnett** [jakobnissen/ScanByte.jl#6]
I notice that ScanByte.jl is tied to using x86 SIMD instructions. As a fallback for other architectures you could use [SIMD.jl](https://github.com/eschnett/SIMD.jl) for code generation.

```Julia
using SIMD

function memchr(::Type{Vec{N,UInt8}}, arr::Vector{UInt8}, ch::UInt8) where {N}
    iota = Vec{N,UInt8}(ntuple(i -> i-1, N))
    lane = VecRange{N}(0)
    @inbounds for i in 0:N:length(arr)-1
        iseq = arr[lane + i+1] == Vec{N,UInt8}(ch)
        if any(iseq)
            return i + minimum(iota | vifelse(iseq, Vec{N,UInt8}(0x00), Vec{N,UInt8}(0xff)))
        end
    end
    return 0
end

@code_native memchr(Vec{64,UInt8}, UInt8.(collect(1:64)), UInt8(3))
memchr(Vec{64,UInt8}, UInt8.(collect(1:64)), UInt8(3))
```

This example shows how to implement `memchr` (without bounds checking etc.) via SIMD.jl. The generated loop kernel is
```
	vpcmpeqb	32(%rdx,%rcx), %ymm0, %ymm3
	vpcmpeqb	(%rdx,%rcx), %ymm0, %ymm4
	vpor	%ymm3, %ymm4, %ymm5
	vpand	%ymm1, %ymm5, %ymm5
	vptest	%ymm2, %ymm5
	jne	LBB0_3
	addq	$64, %rcx
	cmpq	%rcx, %rax
	jne	LBB0_2
```
which is very efficient (but probably less efficient than a hand-coded `memchr`).

The code above could be an example for implementing the more complex `ByteSet` semantics as well.

**Comment by jakobnissen** [comment]
So ScanByte already did used an architechture agnostic path for memchr with a single byte.
I have now changed the implementation so that, if you only pass it a single byte, it just dispatches to libc's `memchr`. In the future, a pure Julia version can be implemented.
